version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file: .env
    ports: ["8000:8000"]
    volumes:
      - ./backend:/app/backend
      - ./chroma_store:/app/chroma_store
      - ./backend/app/content_bank:/app/backend/app/content_bank
    depends_on:
      - minio

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    env_file: .env
    ports: ["8501:8501"]
    volumes:
      - ./frontend:/app/frontend

  minio:
    image: quay.io/minio/minio:RELEASE.2024-08-17T01-24-54Z
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    command: server /data --console-address ":9001"
    ports: ["9000:9000","9001:9001"]
    volumes:
      - ./minio_data:/data
